### ISSUE TITLE
App behaves unexpectedly when time is set to 00:00:00

### ISSUE THREAD

**Issue by andromeda7063** [AnkurAlpha/pomodoro-timer-project#2]
App gets stuck in a loop between "time is over" and "break is over" when no time is provided.

Only possible way to exit seems to be to force quit the app.

![Shot-2024-10-31-184739](https://github.com/user-attachments/assets/01649a07-b139-4ffb-a0f4-45f8ae63d368)
![Shot-2024-10-31-184747](https://github.com/user-attachments/assets/b97806a7-b67b-4eee-bead-5ae5a1251ac4)

**Comment by andromeda7063** [comment]
Info:
OS: archlinux
Python Ver.: 3.12.7
Tcl/Tk Ver.: 8.6.15

**Comment by AnkurAlpha** [comment]
Solved in the following commit [afc8457](https://github.com/AnkurAlpha/pomodoro-timer-project/commit/afc8457becf202792506b66aaf8d3fafdd919daf)
